version: "3.9"

services:
  app:
    image: api-standard
    container_name: api-standard
    build:
      context: .
      dockerfile: Dockerfile-dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./package.json:/app/package.json
      - cache:/cache
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3003:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=api_standard_db
      - DATABASE_USERNAME=api_standard_db
      - DATABASE_PASSWORD=api_standard_db
      - RACK_ENV=development
      - RAILS_ENV=development
      - REDIS_HOST=redis
      - SPROCKETS_CACHE=/cache
      - SHARE_SECRET_KEY=tai-chau
      - BUNDLE_PATH=./vendor/bundle
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.enable=true"
      - "traefik.backend=app"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:api-standard.local.dev;PathPrefix:/"
      - "traefik.tags=app"
    networks:
      - traefik
  db:
    image: bitnami/postgresql:12.7.0
    container_name: api-standard-db
    environment:
      - POSTGRESQL_USERNAME=api_standard_db
      - POSTGRESQL_PASSWORD=api_standard_db
      - POSTGRESQL_DATABASE=api_standard_db
    ports:
      - 3333:3306
    networks:
      - traefik
  redis:
    image: 'bitnami/redis:latest'
    container_name: api-standard-redis
    command: ["redis-server", "--protected-mode", "no"]
    ports:
    - "6383:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_proxy

volumes:
  cache:


